### ISSUE TITLE
After upgrading refile, all old uploaded images have Forbidden 403 response

### ISSUE THREAD

**Issue by rememberlenny** [refile/refile#226] opened 2015-05-13 16:01 UTC
After upgrading the refile-s3 gem and refile, the images uploaded with the past version are all forbidden. Is there a suggested fix for this?

**Comment by jnicklas** [comment] 2015-05-15 14:16
This is very strange. Can you be more specific when you are receiving the error? A stack trace would be helpful!

**Comment by jnicklas** [comment] 2015-05-23 16:03
Are you still experiencing this? We really need more details, otherwise I'll have to close this issue.

**Comment by jnicklas** [comment] 2015-05-25 08:04
Closing this now. Please get back to us if you still have problems with this.

**Closed** 2015-05-25 08:04 UTC
Labels: bug

**Comment by mrsweaters** [comment] 2015-09-11 21:41
FYI, I upgraded to refile 0.6.1 (along with refile-s3 to 2.0) and it upgraded my aws-sdk gem from 2.1.14 to 2.1.20 and broke all images, new and old. Once I downgraded aws-sdk back down to 2.1.14 everything worked again.

**Comment by lomefin** [comment] 2016-06-13 22:26
I also had trouble.
I uploaded files with refile 0.5 and refile-s3 0.1, which brought my some troubles not worth mentioning, so I did an update to refile-s3 0.2

Afterwards, the problem disappeared, but a `forbidden` message appeared. Just that, nothing else.

I reuploaded all files and the problem is now gone. 

The problem is now gone, but I don't know if its going to happen if I update eventually to 0.3
