### ISSUE TITLE
Support multiple file uploads

### ISSUE THREAD

**Issue by jnicklas** [refile/refile#6] opened 2014-11-26 12:51 UTC
Both for direct and for regular uploads.

**Comment by cpowell** [comment] 2015-01-04 15:57
I can confirm that the technique described in the following blog post about CarrierWave is adaptable to the Refile gem:

http://u.osu.edu/hasnan.1/2014/03/30/rails-4-multiple-file-upload-with-carrierwave-nested-form-and-jquery-file-upload/

(I speculate that this is what Piotr Usewicz was referring to.)

**Comment by nhattan** [comment] 2015-01-06 15:12
I'd tried the solution that @cpowell cited above before. It's good but the I've got a problem with presigning. My context is:
```ruby
version.rb
class Version < ActiveRecord::Base
  has_many :attach_files
end

attach_file.rb
class Attach  < ActiveRecord::Base
  attachment :file
  belongs_to :version
end
```
I'm trying to upload multiple files for a version in one form. It'd be awesome if each file is uploaded to fog (such as S3) without hitting app.

**Comment by jnicklas** [comment] 2015-01-14 09:26
I've had some time to think about this, and I think I have a pretty decent way forward for this. Basically along @hubertlepicki's original suggestion. Posting this here for critique.

We add a macro to ActiveRecord called `accepts_attachments_for`, to be used like this:

``` ruby
class Post < ActiveRecord::Base
  has_many :images

  accepts_attachments_for :images, attachment: :file
end
```

Where `attachment: :file` names the column in the `Image` model that has the attachment, the default being `:file`, so it could have been omitted in this case.

This would generate two methods on `Post`, called `images_files` and `images_files=`. These can then be used in a form like this:

``` ruby
form_for @post do |form|
  form.attachment_field :images_files, multiple: true, direct: true
end
```

If we want to get really fancy we could allow:

``` ruby
form_for @post do |form|
  form.attachment_field :images, multiple: :file, direct: true
end
```

But this might just be more confusing.

We build in support into the JS to pick up on the `multiple` attribute, and do the right thing. With the recent changes in how the caching works, it should be relatively simple to preserve form redisplay behaviour.

Obviously this assumes that `Image` has no required fields aside from `file`, but this is reasonable, IMO.

IMO this macro would be small and simple enough to include it in Refile itself, without putting it in another gem.

Thoughts?

**Comment by pusewicz** [comment] 2015-01-14 09:28
Sounds really good to me!

**Comment by geetfun** [comment] 2015-01-16 09:43
+1 for @jnicklas's proposal.

Any other attributes that may need to be edited on :images records could be handled by accepts_nested_attributes_for *after* the initial upload as well.

**Comment by phyxavier** [comment] 2015-01-28 02:25
+1 for @jnicklas's proposal.

**Comment by brandoncc** [comment] 2015-01-28 03:32
+1 for @jnicklas's proposal.

**Comment by xenik** [comment] 2015-02-03 21:14
hi all)+100500 to support multiple file uploads ) i make a software, where i have 1 ticket which must have more than 1 file... as i understand right..Refile cant help to do it now,yeah?

**Comment by arelenglish** [comment] 2015-02-11 03:57
:+1:

**Comment by nhattan** [comment] 2015-02-12 04:08
:+1:

**Comment by andrewcallahan** [comment] 2015-02-12 07:32
:+1:

**Comment by TangRufus** [comment] 2015-02-14 05:21
:+1:

**Comment by emolayi** [comment] 2015-02-18 13:41
We are hoping for a multiple file upload solution.

**Comment by marlosirapuan** [comment] 2015-03-15 18:30
:+1:

**Comment by eddiefisher** [comment] 2015-03-15 22:21
:thumbsup:

**Comment by eddiefisher** [comment] 2015-03-22 15:16
not good way for multiply upload https://gist.github.com/eddiefisher/1e92a4e35f6fd8c60c29

**Comment by janko-m** [comment] 2015-03-29 12:05
I have a different proposal, which wouldn't have to be ORM-specific, it's based on @hubertlepicki's option (1) (serialization). How about serializing the ID and all metadata in a single column (it can remain `<attachment>_id`, or we can rename it to `<attachment>_data`).

```json
{
  "id": 1,
  "filename": "image.jpg",
  "content_type": "image/jpeg",
  "size": 12563
}
```

This would indeed be a backwards incompatible change, but I think it could solve some of our problems, so bear with me.

For multiple uploads, we would just store a serialized array of each file, and I think it shouldn't be difficult to manage creating/updating/deleting of images. This way we wouldn't have to tie ourselved to an ORM. Also, I can't imagine that someone would want to query this data (if they would, I they could just make the column `json` instead of `text` type, and I believe it should work), so I think we're not losing anything with serialization. And I think the implementation would be simple enough to keep it in Refile itself. Also, if someone wants to store additional data, I think should be able to store it in the same column; if not, they can just make a separate model and attachment using Refile's current behaviour, they just wouldn't be able to use multiple-upload file field out-of-the-box.

Also, If we had this, any additional metadata we want to store wouldn't require users to create separate columns in their tables. Separate columns like these is one of the reasons I flew away from Paperclip to CarrierWave. So we could just chuck in #168. It also trivially solves #176.

Thoughts?

**Comment by jnicklas** [comment] 2015-03-29 12:47
@janko-m I did consider that alternative, the reason that I think I prefer the `accepts_attachments_for` solution is that I think it is more practical for users, and also easier to implement.

If we go with allowing multiple images on a column we need to support this everywhere, including in places where it doesn't really makes sense. How would `attachment_image_tag` work with this kind of solution, for example? With the current design of Refile, it would also be pretty awkward to generate URLs to these files. It might be doable by changing the API quite a bit, but it's an invasive change. `attachment_url(@post, :image)[0]` or `attachment_url(@post, :image).each do |url|` just looks weird in a view, IMO. Putting the attachments on a separate model allows us to simply avoid all these awkward questions in the first place.

Also, I just don't think it's as useful. I think this is the kind of thing which seems convenient until you realize that there are a ton of different things you might want to do with the uploaded attachments, all of which are certainly doable if we serialize, but they all become a little awkward. Thing like:

- Sorting the attachments
- Deleting individual attachments
- Adding captions/votes or other other metadata
- Tagging people in uploaded pictures
- All kinds of tracking information (number of downloads, etc)
- Adding additional files

I think a lot of people are going to start out with a mindset of not needing any of that stuff, until they do need it, and then we've kind of painted them into a corner.

**Comment by janko-m** [comment] 2015-03-29 13:39
Yeah, you're right, it indeed is weird with the current design. And in that case `@post.image` should probably also be an array, which is also a bit weird. I still am not able to visualize the downsides of it, though. It wouldn't change the current API when using single upload, it would just behave a differently on multiple upload. I will give it some more thought with your examples in mind.

**Comment by jnicklas** [comment] 2015-04-30 07:56
A question for people on this thread:

I've started working on this, it's coming along nicely. However, I ran into some design decisions I'm unsure about.

1. When directly uploading multiple files, should it trigger the `upload:start`, `upload:complete`, et… events for each file individually, or just once for all of them? My personal preference on this is that triggering them per file is much, much better, so I'm fairly confident that this is the right choice, but I still want to make a note that we could go a different route here. Note that we already have to handle the fact that there might be multiple upload fields in a single form, so assuming we get one single event is a bad assumption. One possibility is to provide both events, but this might just be a bit messy.

2. What happens in a multiple upload when one of the files is invalid or for some other reason cannot be uploaded. The problem is particularly tricky with form redisplays. What if I upload two files, one of which is invalid, should the other file still be preserved? Or should both files be dropped? My feeling on this is that file uploads should be "all or nothing", either *all* of the files are valid, or none of them are. It feels strange to me that we can have a partially successful upload. But again, I'd like to hear your feedback on this.

**Comment by jnicklas** [comment] 2015-04-30 08:05
Another question:

When editing a record and uploading multiple files via this method, should the new files be appended to the list of associated files, or should they replace the existing files? My thinking is that there should probably be a config option for this.

**Comment by brandoncc** [comment] 2015-04-30 18:08
1. I agree, I would prefer per-file triggers. In my use case, I would like to have a counter that tracks current uploads, but can handle that myself if necessary. I don't have a need for an overall trigger as long as I have that counter so I can check if there are zero active uploads left. Others may have a different use case though.

2. I went back and forth, but I think I disagree. I think as a user I would prefer to be presented with an error for each of the failing files, but not have to re-upload the files which were successfully. NOTE: It is a fact that users don't read the page. For this reason, I could be wrong. Also for this reason, your way could result in confused users.

3. My first thought was a config option, so I am glad you felt the same way. I think this is something that will be particular to each use case. I also agree with your default value.

**Comment by jnicklas** [comment] 2015-05-03 17:46
@brandoncc thank you for your well thought-out feedback. You make a good point about the second argument, I'm also on the fence, and I think there's a case to be made for both options. Maybe this should be a config option as well?

**Comment by brandoncc** [comment] 2015-05-03 17:54
I think this comes down to how much "convention over configuration" do you want to have in refile? If you are going for mostly convention over configuration, then this may be one of the things that becomes a convention and people just have to live with. If you would prefer to offer a lot of configuration, then this does seem to be another prime candidate for configuration options.

I think in a perfect world, this would have a sensible default, with a way to configure/override that default. I think in the end, it comes down to the amount of code that each configured code path will require to be maintained. If it doesn't add a ton of code which will then need to be maintained, I say offer a configuration option for it.

I think this sounds like a non-answer, but I did my best to make both arguments, so they can be weighed out fairly.

**Comment by jnicklas** [comment] 2015-05-03 18:05
@brandoncc I think that making question (3) configurable would not add a lot of complexity. On the other hand, making question (2) configurable is probably going to be considerably more difficult.

I've also realized that these two questions interact in a strange way, what happens when I edit an existing record, and upload multiple files, one of which is invalid. With the mix of answers I chose, we end up with pretty strange behaviour, where the files which were previously attached remain, but the newly uploaded files are cleared. I think this is pretty unintuitive.

On the other hand, I think the behaviour of the file input should be the same both before and after I press "Submit". When I attach a couple of files, and then click the file input a second time and select other files, the original files are cleared. It feels to me like this behaviour should be the same when I open the file select dialog after submitting.

I think I might be changing my mind towards:

1. Per file
2. All or nothing
3. Overwrite existing files without a config option

Maybe that's much less flexible, but it seems like the most intuitive behaviour from a user's perspective, I think.

**Comment by brandoncc** [comment] 2015-05-03 18:15
1. I agree
2. I can live with as a user
3. I have a hard time with this one. Real life example: 

I own/created pawnstocker.com. Say a user posts an item for sale this week, and in two weeks it hasn't sold. They decide they want to add another picture of the item. Should they have to re-upload the original pictures? What if they don't have the original pictures anymore but don't want to lose them? Also, if the pictures are large and their internet is slow (as is the case at my work), this adds time that they may not want to spend uploading the images all over again.

To be honest, if #3 is set this way with no way to override, it is probably a deal breaker for my use case. That does not mean that it is not the right decision for refile though.

**Comment by jnicklas** [comment] 2015-05-03 18:25
@brandoncc thank you for your thoughtful input. I'll mull it over a bit.

**Comment by jnicklas** [comment] 2015-05-03 20:03
I just modified #211 to add a `append: true|false` config option, which default to `false`, contrary to what I first suggested. I'm going with the "all-or-nothing" option for (2) for now, if we'd like to change this later we can add a config option, but I feel like it's probably not worth it.

I feel pretty good about #211 now. Everyone who has weighed in with a :+1: on this thread: I'd appreciate it a lot if you'd take the time to test out #211 and see how it works for you, and if you run into any issues. I'd like to get this merged pretty soon.

**Comment by brandoncc** [comment] 2015-05-04 01:29
I wish I could test it for you but I am using Cloudinary and their Carrierwave module in my app. Hopefully some others can. I will definitely be trying it out in my next app. Thanks for all of your hard work!

**Closed** 2015-05-06 12:48 UTC

**Comment by UnderpantsGnome** [comment] 2015-05-13 00:13
@jnicklas I may be seeing an issue with `<%= form.attachment_field :uploads_files, multiple: true %>` without any existing uploads the value of the hidden field created is `[]`, if I view the form after I've uploaded files the value is `[{}, {}]` where there is an empty `{}` for each file I uploaded.

If I submit the form without any changes it deletes all of the previous uploads. If I change the value back to `[]` with the dev tools things work as expected.

**Comment by jnicklas** [comment] 2015-05-13 08:48
@UnderpantsGnome that's strange. Are you using direct, or presigned uploads, or submitting the form manually?

**Comment by UnderpantsGnome** [comment] 2015-05-13 16:55
@jnicklas just plain form submits for now. Planning to move to direct once I get things in place. I have a crude fix in a fork, not sure if it would cause issues in other places.

**Comment by yozzh** [comment] 2015-05-22 09:14
@UnderpantsGnome Are you solved this issue with array of empty objects in hidden field after save multiple files?

**Comment by UnderpantsGnome** [comment] 2015-05-22 15:58
@yozzh I have a working version [here](https://github.com/UnderpantsGnome/refile/tree/fix-for-form-upload-update-eating-attachments) not sure if that's a sane enough change for @jnicklas to want to use.

**Comment by timurkhafizov** [comment] 2015-05-26 13:39
@UnderpantsGnome what if you create a PR with your changes?

This issue forces us to use JS input value nullification.
Also I was able to prevent image being removed via `reject_if` option (please note I do not use `accepts_attachments_for` macro):
```ruby
class Image
  belongs_to :imageable, polymorphic: true
  attachment :picture
end

class Category
  has_one :image, as: :imageable
  accepts_nested_attributes_for :image,
                                reject_if: ->(attr) { JSON.parse(attr[:picture]).empty? }
end
```

**Comment by kirillsalykin** [comment] 2015-05-27 14:40
> If I submit the form without any changes it deletes all of the previous uploads. If I change the value back to [] with the dev tools things work as expected.
Experiencing the same issue now. Not direct upload, not presigned, just submitting form.

Also, is there any way how i can automate removing images by checked not needed?
Something similar to 
```ruby
check_box_tag 'article[remove_image_files_ids[]]', image.id?
```

Thanks!

**Comment by UnderpantsGnome** [comment] 2015-05-27 16:04
@kirillsalykin this is how I'm handling removing existing uploads, this also allows me to set extra properties on the uploads.

app/models/upload.rb

    class Upload < ActiveRecord::Base
      belongs_to :uploadable, polymorphic: true
      attachment :file

      after_destroy :remove_file

      private

        def remove_file
          file.delete
        end

    end

In the container model (Page)

    has_many :uploads, as: :uploadable, dependent: :destroy
    accepts_attachments_for :uploads, attachment: :file
    accepts_nested_attributes_for :uploads, allow_destroy: true

In the view

    <%= f.fields_for :uploads do |upload| %>
      <%= attachment_image_tag(upload.object, :file, :small) %>
      <%= upload.input :primary %>
      <%= upload.input :_destroy, as: :boolean %>
    <% end %>

**Comment by rakelblujeans** [comment] 2015-06-17 03:09
I'm getting an error saying the accepts_attachments_for macro is not defined. Anyone else seeing that?

**Comment by jnicklas** [comment] 2015-06-17 06:15
@rakelblujeans it's not released yet. You need to use the master branch to use it.

**Comment by rakelblujeans** [comment] 2015-06-17 11:55
Ahh thanks. noob mistake!
