### ISSUE TITLE
Support sequential uploads when uploading multiple files with direct: true

### ISSUE THREAD

**Issue by MSchmidt** [refile/refile#478] opened 2016-05-23 14:15 UTC
The built-in support for multiple & direct uploads is great but all files are uploaded at the same time. This causes all of them to upload rather slowly when the user selected a large amount of files. I'd like to set an options (or even have it default) to upload files sequentially. Maybe with an additional option to allow a defined amount of uploads to run in parallel.

This would also increase the chance of getting at least 1 or 2 files through before the user submits the form.

**Comment by abitdodgy** [comment] 2016-06-30 13:53
I wouldn't mind having a bash at this. @jnicklas do you have an idea of how I might go about this? Any guidance suggestions. @MSchmidt have you thought about this yet?

**Comment by sobrinho** [comment] 2018-01-22 15:14
This is interesting but I think it would be complex to do in Refile's core.

I'm closing because we have limited resources to support the project but feel free to open a PR implementing at least the core idea and we can talk about it.

Thanks!

**Closed by sobrinho** 2018-01-22 15:14 UTC
Labels: enhancement

**Comment by abitdodgy** [comment] 2018-01-23 13:36
@sobrinho why would this be complicated? I think we can support direct uploads initially, and that's just a tweak to the JavaScript. Unless I'm missing something?

**Comment by sobrinho** [comment] 2018-01-23 14:34
@abitdodgy direct uploads are already supported, and they are performed sequentially in case of `multiple: true`.

But the issue is about allowing them to occur in parallel or not by using a configuration flag.

I do not have resources (time) to do this by myself but feel free to open an issue and I will be glad to review and test.

**Comment by sobrinho** [comment] 2018-01-23 14:42
Clarifying...

If you use file backend, they will upload sequentially to your rails app, example:

```erb
<%= f.input :images_files, as: :attachment, direct: true, multiple: true %>
```

If you use S3 backend, they will upload sequentially to S3, example:

```erb
<%= f.input : images_files, as: :attachment, direct: true, multiple: true, presigned: true %>
```

What the issue is about is to be able to configure to upload in parallel (concurrent) or sequential.

Being able to configure to upload all at the same time (concurrent requests) may result in some performance gain but I'm not even sure that Amazon S3 allows that.

**Comment by abitdodgy** [comment] 2018-01-23 15:53
@sobrinho I understood the issue to be an option to batch the uploads into chunks. Say a user selected 20 files to upload directly to S3. Instead of uploading all of them at once, Refile.js would batch them into chunks of 10 or whatever, based on user definition. This ensures that uploads with a large number of files go smoothly and don't clog the network, especially in slow connection environments. I don't see this being difficult to do in Refile.js. Unless I'm missing something?

**Comment by sobrinho** [comment] 2018-01-24 12:21
@abitdodgy yes, we are saying almost the same thing here.

The only difference is that Refile uploads file by file instead of all of them at the same time.

My concern here is that this feature opens some questions:

1. How many files should be uploaded at the same time? What's a good default? Should it be configurable?
2. What happens if one file of the chunk fails to upload?
3. What happens if the entire chunk fails to upload?
4. If we are trying to alleviate connection issues, the chunks shouldn't be based on file's size instead of quantity?

Don't get me wrong, I think this is a good feature and I would love to see a PR for that.

But we have some questions to answer before and then someone to implement (I have limited resources to support this project).

Do you want to jump in in this implementation?
