### ISSUE TITLE
Not working "across redisplays"

### ISSUE THREAD

**Issue by abrambailey** [refile/refile#275] opened 2015-06-15 18:39 UTC
Regarding your feature:

`Works across form redisplays, i.e. when validations fail, even on S3`

I am having some trouble with this. Here is my implementation:
```
class Post < ActiveRecord::Base
  attachment :image, content_type: ["image/jpeg", "image/png", "image/gif"]
end

def create
  @post = Post.new(post_params)
end

<%= f.attachment_field :image %>

params.require(:post).permit(:image)
```

Image submission is working, but if the form fails to validate, the image is lost on form reload.

**Comment by jnicklas** [comment] 2015-06-15 19:25
Just to clear up a misconception, if the image itself is invalid, it will be lost on form reload, that's expected behaviour. After all, how would the image suddenly become valid? The image is only kept if another validation (say on the post title) fails.

**Comment by abrambailey** [comment] 2015-06-15 20:56
@jnicklas Sorry, I can see how this issue was confusing. I just trimmed my Post model code down for simplicity. The error is occurring when a different attribute causes the validation error, not the image.

**Comment by abrambailey** [comment] 2015-06-15 21:07
Here is the params hash
```
{"utf8"=>"✓", "authenticity_token"=>"8ssP8o9kTiACr/IazHgY9LqF1puGEiYNynuUGAx5IcBnWaDUR+8fIupxH+WBBJ+36JtFcw95QVyiKqnc3So6iw==", "post"=>{"post_topic_ids"=>[""], "title"=>"", "content"=>"", "blurb"=>"", "event_time"=>"", "event_date"=>"", "location"=>"", "image"=>"{\"id\":\"d4acfe06d57d009f101781fead5233dcf8e2cea6b051c5d1c97d381ef747\",\"filename\":\"81h3tH7rsvL.jpg\",\"content_type\":\"image/jpeg\",\"size\":33723}", "type"=>"Opportunity"}, "commit"=>"Create Opportunity", "controller"=>"enterprise/posts", "action"=>"create"}
```

**Comment by jnicklas** [comment] 2015-06-16 07:56
The "No file chosen" is expected. We can't change the value of a file field and have that do something sensible. The file metadata is kept in a hidden field, which is added just ahead of the file field.

Looking at the params hash, it seems that it contains a metadata representation of a file, which would be expected after a failed validation. Looks good in other words.

I can't immediately see what's wrong. What you're doing should work. Sorry I can't be of much more help than that.

**Comment by abrambailey** [comment] 2015-06-16 15:11
That's OK. I appreciate it! Basically even though the params hash looks good, if I resubmit the form (without re-adding the image) the Post is saved with no image. Does that makes sense?

**Comment by jnicklas** [comment] 2015-06-16 15:13
Hmm, that's not supposed to happen at least. If you can upload your code somewhere I can take a look. Short of that I'm out of ideas.

**Comment by abrambailey** [comment] 2015-06-16 15:28
@jnicklas I can't really upload the entire project, but here are the relevant files (some rough edges, as this is a work in progress) ... Thanks https://gist.github.com/abrambailey/5c69eb5ffb16962e253f

**Comment by jnicklas** [comment] 2015-06-16 15:32
Sorry, that's not something I can work with. You're going to have to prepare something actually executable where you're experiencing the problem.

**Comment by abrambailey** [comment] 2015-06-16 18:31
@jnicklas So, I think we have found the issue. It has to do with our usage of STI, and losing the instance variables from `@post`
```
@post.instance_variable_get(:@image_attacher)
#<Refile::Attacher:0x007fb6525ea2f8 @record…
@post.becomes(Post).instance_variable_get(:@image_attacher)
nil
```
The becomes is losing the instance variable that stores the attachment info

**Comment by jnicklas** [comment] 2015-06-16 20:13
I maintain that STI is the devil and shouldn't ever be used ;)

Ugh, not sure what we can do about this.

**Comment by abrambailey** [comment] 2015-06-16 20:24
:smiling_imp: <-- STI

**Comment by abrambailey** [comment] 2015-06-22 17:29
So, this seems to work (dirty, but owell):
```
<%= form_for([:enterprise, @post.becomes(Post)], html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% f.object = @post.becomes(@post.class) %>
  <% @post.instance_variables.each { |iv| f.object.instance_variable_set(iv, @post.instance_variable_get(iv)) } %>
```

**Comment by jnicklas** [comment] 2015-07-06 16:59
So I'm not really sure what to do with this issue. I really don't want to dive into the inner workings of STI to find out what's going on. I'd tell people not to use STI, but then someone might have contracted STI from someone else (see what I did there?), and they might not have a choice.

So I think the verdict on this is going to be that *I'm* not going to do anything about it, because I can't think of many less fun uses of my time. If someone else wants to, I'd appreciated it a lot. I'm closing *this* issue, because it contains a lot of superfluous information, not actually relevant to the STI issue. Again, someone else is welcome to open a new issue which summarizes exactly what's going on, but it's not going to be me.

**Closed by jnicklas** 2015-07-06 16:59 UTC

**Comment by abrambailey** [comment] 2015-07-06 18:42
Thanks for the awesome gem @jnicklas .. Fortunately we got this working, so no sweat!
