### ISSUE TITLE
Nested Multiple Uploads

### ISSUE THREAD

**Issue by jcuenod** [refile/refile#320] opened 2015-08-10 21:30 UTC
I'm trying to set up what amounts to a gallery structure.

User creates a `gallery` object which has a name and `accepts_nested_attributes_for :photo` (gallery `has_many :photos` and photo `belongs_to :gallery`. Photos have an `:image` attachment.

So the final product I'm hoping to have is a form that, when submitted creates the gallery and accepts multiple image uploads, storing each in a photo object. Is this possible at present?

**Comment by jcuenod** [comment] 2015-08-11 21:44
Okay, I've made some progress now with `accepts_attachments_for` (probably because I'm actually running `master` now) but it fails on validations.

Also, just to note, it took me a while to realise that the form that takes the `:images_files` field is the parent form, rather than a nested form (which is how I've always handled nested models).

**Comment by chrise86** [comment] 2015-08-21 11:29
I've got a similar issue, but I want to use nested forms (using Cocoon) and handle the image attachment in the nested fields. The problem is that Refile only seems to update the 1 input with the latest image selection, rather than allowing multiple inputs to be updated.

**Comment by DmitrySharikov** [comment] 2015-08-21 11:31
@chrise86 that's right I've got same

**Comment by chrise86** [comment] 2015-08-21 11:34
I think this is related to https://github.com/refile/refile/issues/300

**Comment by jnicklas** [comment] 2015-09-09 13:54
Seems like the original issue is solved? Closing.

**Closed** 2015-09-09 13:53 UTC
Labels: bug

**Comment by jcuenod** [comment] 2015-09-09 17:38
I certainly managed to fix my problem. Thanks
