### ISSUE TITLE
Multiple files upload is broken on rack-test

### ISSUE THREAD

**Issue by wojtekmach** [refile/refile#412] opened 2015-12-29 19:52 UTC
Hi, I was trying to test multiple files upload and noticed it doesn't work well on rack-test. Everything is OK on javascript capybara drivers though.

Here's a repro: https://github.com/wojtekmach/refile/commit/90380c6fb8724c04cd9a2b939d81c6178026a7e5

I guess there're 2 ways to address this:

1. change rack-test: I guess it would be OK and the behavior would be similar to other drivers like poltergeist
2. change refile: instead of assuming that the first object in the array (e.g.: `{document_files: ["{}", "#<Rack::Test::UploadedFile>", ...]}`) is JSON string for cache - make it as a separate parameter, e.g. `{document_files: [#<Rack::Test::UploadedFile>, ...], document_files_cache: "{}"}`. Seems more elegant to me.

What do you think?

**Comment by jnicklas** [comment] 2015-12-29 22:39
The problem is that RackTest doesn't handle this very well. Nor does Selenium. This is why we use Poltergeist for Refile's own test suite, since it's the only Capybara driver with decent multiple-file support. In fact there are several other issues with RackTest's file implementation which don't work well with Refile. I don't think it's a good idea to work around those in a worse way in Refile itself. Fixing RackTest, or rather Capybara's RackTest driver, is the better solution.

**Comment by jnicklas** [comment] 2015-12-29 22:39
Closing this as there's nothing really to be done within Refile.

**Closed by jnicklas** 2015-12-29 22:39 UTC
